version: '3.8'

services:
  web:
    image: flask
    ports:
      - "5000:5000"
    environment:
      DB_NAME: your_db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_HOST: localhost
      DB_PORT: 5432
